
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testOrg.test1
  description: This is a dummy col proj
  tags:
    - ansible
    - collection
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: KB-perByte/Testdxccd
  links:
    - url: https://devspaces.apps.y1a9e1j9r7y1i8l.cbm5.p1.openshiftapps.com/#https://github.com/#https://github.com/KB-perByte/Testdxccd
      title: OpenShift Dev Spaces
      icon: web
spec:
  type: collection-project
  system: Sagar
  lifecycle: production
  owner: Sagar
